# 应用名称
spring.application.name=sbc-user
server.context-path=/
server.port=8080

# 注册中心eureka
eureka.client.serviceUrl.defaultZone=http://node1:8888/eureka/

# 是否打开swagger
swagger.enable = true


#日志
logging.level.com.crossoverJie.sbcuser.controller=trace

# 并发线程配置
concurrent.core.size = 20
concurrent.max.size  = 20
concurrent.blockqueue.size= 100

# 执行环境 local,dev,test,pro
excute.env = local

# 开启 Feign Hystrix 降级
feign.hystrix.enabled=true

# Hystrix 超时配置 (订单服务调用)
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=3000
hystrix.command.default.circuitBreaker.requestVolumeThreshold=10
hystrix.command.default.circuitBreaker.sleepWindowInMilliseconds=5000

# Feign + Ribbon 超时配置
ribbon.ReadTimeout=5000
ribbon.ConnectTimeout=3000